### ISSUE TITLE
Extra headers during initialization

### ISSUE THREAD

**Issue by aderihoJD** [trinodb/trino-js-client#485]
Possibility to provide extra / additional request headers will help to solve some issues with connection to Trino inside cluster.
When some service setup inside one k8 cluster with Trino, you have a possibility to call it via http, but you have to pass `X-Forwarded-Proto: "https"` as axios request header.
So, would be great to extend **ConnectionOptions** interface (f.e. with **extraHeaders** property) and pass them to **query** method for **headers**.

**Comment by Amatrasan** [comment]
Add possibility in [MR] (https://github.com/regadas/trino-js-client/pull/568).
