### ISSUE TITLE
Axios 1.7.4 Update

### ISSUE THREAD

**Issue by kobalski** [trinodb/trino-js-client#637]
Axios 1.7.4 fixes security [issue](https://github.com/advisories/GHSA-8hc4-vh64-cxmj)

Could you please upgrade axios version?

**Comment by neeppy** [comment]
Fix got merged but never published to `npm`. When is that going to be published?

**Comment by mosabua** [comment]
We are working on updating our publishing process. Trying to get to it as soon as we can.

**Comment by kasparlaurenz** [comment]
any updates on this?

**Comment by regadas** [comment]
Will try to make it happen this week sorry about the delay

**Comment by mosabua** [comment]
Also .. there is an update to 1.7.7 that we might want to verify and ship before we release

**Comment by yuokada** [comment]
This issue has been fixed.
https://github.com/trinodb/trino-js-client/releases/tag/v0.2.4
https://github.com/trinodb/trino-js-client/commit/a672c48fba7a4991b56f2ac07d3c88be67de3e23
